# -*- coding: utf-8 -*-
"""EDA_Terrorism.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xPeyNf6J_fYiL7b9Iq10xWf6uKvPzsCA
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Loading data from url
data=pd.read_csv('global.csv',encoding='ISO-8859-1', low_memory=False)
print("Data imported successfully")

df = data
df

data.describe()

data.shape

data.columns

data.info()

data.rename(columns={'iyear':'Year','imonth':'Month','iday':'Day','country_txt':'Country','provstate':'state','region_txt':'Region','attacktype1_txt':'AttackType','target1':'Target','nkill':'Killed','nwound':'Wounded','summary':'Summary','gname':'Group','targtype1_txt':'Target_type','weaptype1_txt':'Weapon_type','motive':'Motive'},inplace=True)

new_data=data[['Year','Month','Day','Country','state','Region','city','latitude','longitude','AttackType','Killed','Wounded','Target','Summary','Group','Target_type','Weapon_type','Motive']]

new_data

new_data.columns #extracted data contains only 18 columns after optimising

new_data.shape

new_data.isnull().sum()

numeric_data = new_data.select_dtypes(include=['number'])

# Compute the correlation matrix
corr = numeric_data.corr()

# Set the figure size
plt.figure(figsize=(10, 10))

# Create and display the heatmap
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.show()

plt.figure(figsize=(40,20))
new_data.hist(figsize=(20,20))

pd.crosstab(new_data.Year, new_data.Region).plot(kind='area',figsize=(15,5))
plt.title('Terrorist Activities by Region in each Year')
plt.ylabel('Number of Attacks')
plt.grid()
plt.show()

plt.subplots(figsize=(15, 5))

# Create a countplot
sns.countplot(x='Year', data=new_data)

# Rotate the x-axis labels
plt.xticks(rotation=90)

# Set the title of the plot
plt.title('Number Of Terrorist Activities Each Year')

# Add a grid
plt.grid()

# Show the plot
plt.show()

Year=new_data.Year.value_counts().to_dict()
rate=((Year[1996]-Year[1970])/Year[1996])*100
print(Year[1970],'attacks happened in 1970 ')
print(Year[1996],'attacks happened in 2017')
print('Total number of attacks from 1970 has increased by',np.round(rate,0),'% till 2017')

plt.figure(figsize=(16,3))
sns.countplot(x = new_data['AttackType'], order = new_data['AttackType'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Method')
plt.title('Method of Attack')
plt.show()

plt.figure(figsize=(16,5))
sns.countplot(x = new_data['Target_type'], order=new_data['Target_type'].value_counts().index)
plt.xticks(rotation=70)
plt.xlabel('Type')
plt.title('Type of Target')
plt.grid()
plt.show()

fig,axes = plt.subplots(figsize=(16,5),nrows=1,ncols=2)
sns.barplot(x = new_data['Country'].value_counts()[:20].values, y = new_data['Country'].value_counts()[:20].index, ax=axes[0]);
axes[0].set_title('Terrorist Attacks per Country')
sns.barplot(x=new_data['Region'].value_counts().values, y=new_data['Region'].value_counts().index, ax=axes[1])
axes[1].set_title('Terrorist Attacks per Region')
fig.tight_layout()
plt.show()

df=new_data.groupby(['Country'],as_index=False).count()

max_count=df['Year'].max()
max_id=df['Year'].idxmax()
max_name=df['Country'][max_id]
min_count=df['Year'].min()
min_id=df['Year'].idxmin()
min_name=df['Country'][min_id]

print(max_name,'has suffered the maximum number of terror attacks of',max_count)
print(min_name,'has suffered the minimum number of terror attacks of',min_count)

plt.subplots(figsize=(11,5))
sns.barplot(y=new_data['Group'].value_counts()[1:12].index,x=new_data['Group'].value_counts()[1:12].values)
plt.title('Most Active Terrorist Organizations')
plt.show()

data_after = new_data[new_data['Year']>=1971]
fig,ax = plt.subplots(figsize=(15,10), nrows=2, ncols=1)
ax[0] = pd.crosstab(new_data.Year, new_data.Region).plot(ax=ax[0])
ax[0].set_title('Change in Regions per Year')
ax[0].legend(loc='center left', bbox_to_anchor = (1,0.5))
ax[0].vlines(x=2001, ymin=0, ymax=7000, linestyles='--')
pd.crosstab(data_after.Year,data_after.Region).plot.bar(stacked=True, ax=ax[1])
ax[1].set_title('After Declaration of War on Terror (2001-2017)')
ax[1].legend(loc='center left', bbox_to_anchor = (1,0.5))
plt.show()

print('Country with Highest Terrorist Attacks:',df['Country'].value_counts().index[0])
print('Regions with Highest Terrorist Attacks:',df['Region'].value_counts().index[0])
print('Maximum people killed in an attack are:',df['Killed'].max(),'that took place in',df.loc[df['Killed'].idxmax()].Country)